set(Eigen3_include_path /usr/include/eigen3)
set(opencv4_include_path /usr/local/include/opencv4)
set(opencv4_libary_path /usr/local/lib)
set(BOOST_INC /usr/local/include/)
set(BOOST_LIBS /usr/local/lib)